name: Auto Football Conductor
on:
  workflow_dispatch:
  schedule:
    - cron: '16 08 * * *'

jobs:
  run-conductor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install requests beautifulsoup4
      - name: Run Scraper
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python daily_conductor.py
