name: Auto Forward LiveScore Posts

on:
  schedule:
    - cron: '45 20 * * *' # هر شب ۰۰:۱۵ بامداد به وقت ایران
  workflow_dispatch:

jobs:
  forward_posts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run Forwarder Script
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          python forwarder.py
