name: Daily Conductor Forwarder

on:
  schedule:
    # ساعت 06:00 به وقت UTC برابر با 09:30 صبح به وقت ایران
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  check_and_forward:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests beautifulsoup4

      - name: Run Script
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          SOURCE_CHANNEL: 'SPORTinoTV'
          FILTER_TEXT: 'کنداکتور'
        run: python forwarder.py
