name: Gold and Currency Daily Report

on:
  workflow_dispatch: # اجرای دستی از گیت‌هاب
  repository_dispatch:
    types: [trigger-gold]
  schedule:
    # 09:08 AM Iran Time (UTC+3:30) => 05:38 UTC
    - cron: '38 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pillow arabic-reshaper jdatetime pytz

      - name: Run Script
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          python gold_report.py

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: gold-dollar-report-image
          path: Gold_Dollar_Report.png
