name: Iran Outage Reporter

on:
  workflow_dispatch: # امکان اجرای دستی
  repository_dispatch:
    types: [trigger-outage]
  schedule:
    # 07:13 AM Iran Time (UTC+3:30) => 03:43 UTC
    - cron: '43 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4 reportlab arabic-reshaper python-bidi jdatetime pytz

      - name: Run Script
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          python main.py

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: outage-report-pdf
          path: Doroud_Outage_Report.pdf
